const data = {
    products: [
        {
            _id:'1',
            name:'The Mayan Calendar (2012)',
            category: 'strategy', 
            image: '/images/p1.jpg',
            price: 44.39,
            age: '13+',
            players: '2-4',
            time: '90 min',
            brand: 'Czech Games Edition',
            rating: 4.5,
            numReviews: 310,
            description: 'Lead your people, build monuments and make offerings to earn the favour of the gods.',
        },
        {
            _id:'2',
            name:'Underwater Cities (2018)',
            category: 'strategy', 
            image: '/images/p2.jpg',
            price: 59.76,
            age: '12+',
            players: '1-4',
            time: '80-150 min',
            brand: 'Delicious Games',
            rating: 4.0,
            numReviews: 123,
            description: 'Develop future cities on the seafloor through politics, production, and science.',
          },
          {
            _id:'3',
            name:'Marvel Champions (2019)',
            category: 'card game', 
            image: '/images/p3.jpg',
            price: 59.95,
            age: '14+',
            players: '1-4',
            time: '45-90 min',
            brand: 'Fantasy Flight Games',
            rating: 4.0,
            numReviews: 223,
            description: 'Battle Marvel villains with unique teams of iconic heroes in this LCG.',
          },
          {
            _id:'4',
            name:'Too Many Bones (2017)',
            category: 'adventure', 
            image: '/images/p4.jpg',
            price: 259.98,
            age: '12+',
            players: '1-4',
            time: '60-120 min',
            brand: 'Chip Theory Games',
            rating: 5.0,
            numReviews: 1223,
            description: 'Toss gobs of unique dice in an epic adventure en route to a final boss showdown.',
          },
          {
            _id:'5',
            name:'AuZtralia (2018)',
            category: 'strategy', 
            image: '/images/p5.jpg',
            price: 69.99,
            age: '13+',
            players: '1-4',
            time: '30-120 min',
            brand: 'SchilMil Gamess',
            rating: 3.0,
            numReviews: 413,
            description: 'Explore and settle alternate-history 1930s Australia as Cthulhu awakes.',
          },
          {
            _id:'6',
            name:'Sleeping Gods (2021)',
            category: 'adventure', 
            image: '/images/p6.jpg',
            price: 84.99,
            age: '13+',
            players: '1-4',
            time: '60-1200 min',
            brand: 'Red Raven Games',
            rating: 5.0,
            numReviews: 13,
            description: 'Voyages of the steamship "Manticore" and her crew on the Wandering Sea.',
          },
          {
            _id:'7',
            name:'The Siege of Runedar (2021)',
            category: 'fantasy', 
            image: '/images/p7.jpg',
            price: 126.98,
            age: '10+',
            players: '1-4',
            time: '60-90 min',
            brand: 'Ludonova',
            rating: 0.0,
            numReviews: 0,
            description: 'Players take on the role of dwarves charged with defending the walls of Runedar.',
          },
          {
            _id:'8',
            name:'Lost Ruins of Arnak (2020)',
            category: 'adventure', 
            image: '/images/p8.jpg',
            price: 59.95,
            age: '12+',
            players: '1-4',
            time: '30-120 min',
            brand: 'Czech Games Edition',
            rating: 4.0,
            numReviews: 707,
            description: 'Explore an island to find resources and discover the lost ruins of Arnak.',
          },
          {
            _id:'9',
            name:'Spirit Island (2017)',
            category: 'card game', 
            image: '/images/p9.jpg',
            price: 19.99,
            age: '13+',
            players: '1-4',
            time: '90-120 min',
            brand: 'Greater Than Games',
            rating: 4.5,
            numReviews: 27,
            description: 'Island Spirits join forces using elemental powers to defend their home from invaders.',
          },
          {
            _id:'10',
            name:'7 Wonders Duel (2015)',
            category: 'fantasy', 
            image: '/images/p10.jpg',
            price: 26.99,
            age: '10+',
            players: '2',
            time: '30 min',
            brand: 'Repos Production',
            rating: 3.5,
            numReviews: 627,
            description: 'Science? Military? What will you draft to win this head-to-head version of 7 Wonders?',
          },
          {
            _id:'11',
            name:'Gaia Project (2017)',
            category: 'fantasy', 
            image: '/images/p11.jpg',
            price: 99.95,
            age: '12+',
            players: '1-4',
            time: '60-150 min',
            brand: 'Feuerland Spiele',
            rating: 4.5,
            numReviews: 6127,
            description: 'Expand, research, upgrade, and settle the galaxy with one of 14 alien species.',
          },
        
    ],
};

export default data;